version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./uploads:/app/uploads  # Локальное хранилище файлов

  audio_db:
    container_name: audio_db
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword321!
      POSTGRES_DB: audio_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: