global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'audio_fastapi'
    static_configs:
      - targets: ['app:8000']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']