"""Fix table user

Revision ID: 76b6f2187e8b
Revises: 42ca373f3d61
Create Date: 2025-03-30 16:44:24.966741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76b6f2187e8b'
down_revision: Union[str, None] = '42ca373f3d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('yandex_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_yandex_id'), 'user', ['yandex_id'], unique=True)
    op.drop_constraint('user_referred_by_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'referred_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referred_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key('user_referred_by_fkey', 'user', 'user', ['referred_by'], ['id'])
    op.drop_index(op.f('ix_user_yandex_id'), table_name='user')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'yandex_id')
    # ### end Alembic commands ###
